//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment_B_DbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Assignment()
        {
            this.Courses = new HashSet<Course>();
        }
    
        public int AssignmentID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> SubmitDate { get; set; }
        public Nullable<int> OralMark { get; set; }
        public Nullable<int> TotalMark { get; set; }
        public string Type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course> Courses { get; set; }



        public void ViewAllAssignments()
        {
            Console.WriteLine($"{AssignmentID,-15}{Title,-15}{Description,-15}{SubmitDate,-25}{OralMark,-15}{TotalMark,-15}{Type}");
        }

    }
}
